### ISSUE TITLE
Link to Twitch video does not exist

### ISSUE THREAD

**Issue by sliedig** [aws-samples/aws-net-guides#1]
https://www.twitch.tv/videos/246611593 does not exist.

**Comment by jpantuso** [comment]
And still doesn't exist

**Comment by kneekey23** [comment]
hi to both of you, where did you see this url? Somewhere in these guides? Or on the videos page of the .NET Developer Center. What is the name of this video you are trying to access? Thanks!

**Comment by sliedig** [comment]
See link on https://github.com/aws-samples/aws-net-guides/blob/master/Serverless/Serverless%20Web%20App%20with%20React%2C%20DynamoDb%2C%20and%20X-Ray/README.md

**Comment by kneekey23** [comment]
this is now fixed, my apologies! here is the link for convenience: https://www.youtube.com/watch?v=r0YtDzNKwEU
