### ISSUE TITLE
AWS Lambda Serverless .Net Core +angular Cli - Forbidden Error

### ISSUE THREAD

**Issue by IyyappanAmirthalingam** [aws-samples/aws-net-guides#2]
Hi,

I am trying to deploy .net core spa with angular cli in lambda serverless model. when I try to access the lambda URL it shows 403-Forbidden error.

.Net core - 2.1
Angular Cli - 6.0.0

Lambda URL as follows
https://p1vu9hp2a8.execute-api.us-east-2.amazonaws.com/Prod 

Kindly help me fix this issue.

Thanks
Iyyappan Amirthalingam

**Comment by kneekey23** [comment]
Hi! If you are using Spa and deploying to lambda as a web app, you will need to set your base url in the angular app to be /prod. it's trying to access the root of your project but the entire root is now at /prod. In react, you go to into a json settings file to set the homepage url, not sure where this is in react.

**Comment by IyyappanAmirthalingam** [comment]
Hi,
Thanks for your note. I tried updating the <base href="/"> in the index.html of the angular app but still having the same issue.

Thanks

**Comment by kneekey23** [comment]
you updated the base href to /Prod and no luck? Does your IAM user have both lambda and api gateway permissions? Are you making any other aws calls that your IAM user might not have permissions for?

**Comment by IyyappanAmirthalingam** [comment]
I have added the following policies to the lambda execution role 
1. AWSLambdaFullAccess
2. AmazonS3FullAccess
3. AmazonAPIGatewayInvokeFullAccess
4. AWSLambdaBasicExecutionRole

**Comment by kneekey23** [comment]
when i open your lambda link, it still shows base href = '/' not 'Prod/' ? Have you redployed since updating this?

**Comment by kneekey23** [comment]
In my react app, I had to update this in 3 different places which I eventually just made a variable that changes based on dev vs prod. but when I was first testing, I manually changed each place and got it to work

**Comment by kneekey23** [comment]
Here are the three files I am talking about just for reference in a React Frontend:
1. This one is for my api calls to my .net backend
https://github.com/aws-samples/aws-net-guides/blob/master/Serverless/Serverless%20Web%20App%20with%20React%2C%20DynamoDb%2C%20and%20X-Ray/ClientApp/src/components/api-config.js
2. sets base url
https://github.com/aws-samples/aws-net-guides/blob/master/Serverless/Serverless%20Web%20App%20with%20React%2C%20DynamoDb%2C%20and%20X-Ray/ClientApp/src/index.js
3. sets home page url (for me this was the full lambda link so yours would be https://p1vu9hp2a8.execute-api.us-east-2.amazonaws.com/Prod)
https://github.com/aws-samples/aws-net-guides/blob/master/Serverless/Serverless%20Web%20App%20with%20React%2C%20DynamoDb%2C%20and%20X-Ray/ClientApp/package.json

Hope this helps

**Comment by allenmichael** [comment]
Hi @IyyappanAmirthalingam,

Can you try adding `"deployUrl": "./Prod",` to the `apps` section of `.angular-cli.json`?

It should look like this:
`.angular-cli.json
```json
{
...
"apps": [
    { 
      ...
      "deployUrl": "./Prod",
      ...
    }
  ]
}
`

Have you considered deploying your Angular app to S3's static hosting and just using your .NET app as the API for the Angular app? You won't need to set these values if hosting your Angular app since S3 won't have an API stage (`/Prod` in this case) added to the URL.

**Comment by IyyappanAmirthalingam** [comment]
Thanks a lot Nicki Klein. 

After updating the base href = 'Prod/' the issue resolved. 

Thank you so much.

**Comment by natepaxton** [comment]
Changing the base ref here resolves the 403, but breaks the routing for the angular app.  Is there a configuration solution?
