### ISSUE TITLE
Append Referenced Documents

### ISSUE THREAD

**Issue by zisom-stamps** [aws-samples/aws-net-guides#22]
This is the Documentation that should be referenced as it's directly related to the configuration file you have us set up. Regardless thank you for creating this tutorial! i need to find more info about this particular way of configuring metrics to go to Cloudwatch, and it took me a long time to finally find this link since the method in the tutorial is not mentioned in the CloudWatch documentation pages

https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/QuickStartWindows2016.html

**Comment by steveataws** [comment]
Thanks for the suggestion, and apologies it took us so long to start monitoring and updating this repo of guides. I've included the suggested link in the guide readme.
