### ISSUE TITLE
DynamoDBSvcLib\DynamoDBSvcLib\AWSSvcAppLib.csproj is missing 

### ISSUE THREAD

**Issue by gchadid** [aws-samples/aws-net-guides#3]
Iwas trying to run the serverless sample project Musiquizza-React, but it has a missing reference to AWS cApLib.csproj, i did a clone of the aws-net-guides repo, but i could not find it.

<img width="210" alt="missingproject" src="https://user-images.githubusercontent.com/10290878/44798467-29782e00-ab77-11e8-9041-3eced9e0b41f.PNG">

Tnks

**Comment by kneekey23** [comment]
so sorry about that! just pushed the additional solution that has been added as an assembly to this project. get latest if you can and you will see a new folder called DynamoDbSvcLib
