### ISSUE TITLE
Elastic Beanstalk Support for Net6 on Gravitron

### ISSUE THREAD

**Issue by bobskigit** [aws-samples/aws-net-guides#36]
When will AWS ship the default gravitron instances on Elastic beanstalk with .NET 6 support?

In fact when will all the Elastic beanstalks have .NET 6 runtime support?

**Comment by joshongithub** [comment]
Hi @bobskigit: 

We haven't announced a delivery date for AWS Elastic Beanstalk support for .NET 6 on either X86_64 or Graviton.  Support is planned in the near future. An [Issue](https://github.com/aws/elastic-beanstalk-roadmap/issues/216) was opened on their Public Roadmap for .NET 6 support. In addition to following this .NET 6 support guide, you can subscribe to that Issue to track the latest on support. 

In the meantime, to use .NET 6 with AWS Elastic Beanstalk, you can use the .NET [Publish self-contained](https://docs.microsoft.com/en-us/dotnet/core/deploying/#publish-self-contained) option to package the .NET 6 runtime with your application code. 

Josh.

**Comment by bobskigit** [comment]
You need to specificy the runtime

dotnet publish $PROJECT_NAME --output $WHERE --runtime win-x64 --self-contained true

**Comment by MrAdam** [comment]
@bobskigit, if you read my comment again, you can see that I specify that I run 64bit Amazon Linux, and that I have verified that the output is `linux-64`.  If you run the `dotnet eb deploy-environment` command that I specified, you can also see from the console logs that it appends a `--runtime linux-64` to the `dotnet publish` command that it executes.

**Comment by MrAdam** [comment]
I made a mistake when creating the auto-scaling group, as I read `arm64` as `amd64`, and thought that x86 would be 32-bit.
![image](https://user-images.githubusercontent.com/297282/145557421-72be8116-0030-4b32-ab16-76c31596ea8f.png)

**Comment by joshongithub** [comment]
It appears this issue was resolved. I'll close the issue.
