### ISSUE TITLE
Lambda DotNet 6 support?

### ISSUE THREAD

**Issue by Simonl9l** [aws-samples/aws-net-guides#38]
When is it planned to directly support DotNet 6 (Net 6) runtime Lambda?

Whist it seems it can be done with a custom runtime, it would be great of this was standard.

**Comment by ageroh** [comment]
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '6.0.0' was not found.
- The following frameworks were found:
3.1.20 at [/var/lang/bin/shared/Microsoft.NETCore.App]
You can resolve the problem by installing the specified framework and/or SDK.....


I am quiting now AWS moving to Azure... oh god..

**Comment by jwschram** [comment]
> When is it planned to directly support DotNet 6 (Net 6) runtime Lambda?
> 
> Whist it seems it can be done with a custom runtime, it would be great of this was standard.

We really need a date for this. The [AWS .NET 6 guide](https://aws.amazon.com/blogs/developer/net-6-on-aws/) was released on 2021-11-17 and mentions lambda runtime, this repo says that _[In the near future, managed instances with .NET 6 runtime will be preinstalled...](https://github.com/aws-samples/aws-net-guides/tree/master/RuntimeSupport/dotnet6)_ but that's not enough for enterprise planning.

**Comment by jqing** [comment]
I thought after the dotnet core 3.1 support disaster, AWS will do much better for .net 6. well, 3 years later, nothing changed. 

dotnet core 3.1 released on Dec 3, 2019 and we got the official runtime for lambda on  MAR 31, 2020

dotnet 6 released on Nov 8, 2021 and today still no any timeline for the runtime support for lambda.

Feels like dotnet support in AWS is done by some volunteers and nobody take it seriously.

**Comment by joshongithub** [comment]
Hi All:

We have released .NET 6 support for AWS Lambda managed runtime. Here is a blog post that provides more information:
https://aws.amazon.com/blogs/compute/introducing-the-net-6-runtime-for-aws-lambda/

I'll close this issue. 

Josh.
