### ISSUE TITLE
EC2 net 6 managed images

### ISSUE THREAD

**Issue by trossr32** [aws-samples/aws-net-guides#41]
Hi,

Managed .net 6 images for EC2 have been referenced [here](https://github.com/aws-samples/aws-net-guides/tree/master/RuntimeSupport/dotnet6) as '_In the near future Elastic Beanstalk will provide managed images that have .NET 6 preinstalled._' for months. Whilst I realise that one can use a self-contained deploy from Visual Studio, that seems to be of little use when attempting to use a codepipeline workflow for deploying apps via elastic beanstalk.

Could you please give a concrete date for when this functionality will be available, as not having any idea when this will be supported is impacting our project planning (and .net 6 has been out for 4 months now!)

Thanks

**Comment by joshongithub** [comment]
Hi Rob:

Thank you for your patience. We don't have a date, but the AWS Elastic Beanstalk team is planning on adding support. They have two items related to .NET 6 on their [Roadmap](https://github.com/aws/elastic-beanstalk-roadmap) that you can track:

- [.NET 6 on Linux Support](https://github.com/aws/elastic-beanstalk-roadmap/issues/238) 
- [.NET 6 on Windows Server support](https://github.com/aws/elastic-beanstalk-roadmap/issues/216) 

Josh.

**Comment by joshongithub** [comment]
Hi [trossr32](https://github.com/trossr32):

.NET 6 has been added to on AWS Elastic Beanstalk Amazon Linux 2 managed images. The 
[release notes](https://docs.aws.amazon.com/elasticbeanstalk/latest/relnotes/release-2022-03-31-linux.html) have more detail.

Is your company using Windows or Linux images?

Josh.

**Comment by trossr32** [comment]
Windows. We've set up a direct line of communication with AWS representatives who are looking into this, so I'll close the issue.
